### ISSUE TITLE
Не могу получить доступ к анкете на 2021 год

### ISSUE THREAD

**Issue by gshigin** [Dyakonov/PZAD#5]
Здравствуйте! Я являюсь студентом 4 курса ФКИ МГУ. В этом году нам предоставили широкий выбор спецкурсов по выбору, среди которых есть и ваш. Однако, не получается заполнить форму, так как доступ к ней закрыт.  Что можно с этим сделать?
![image](https://user-images.githubusercontent.com/57219774/132957409-25757c5e-2f60-4f8e-8cd7-d8cfcb68ffdf.png)

**Comment by Dyakonov** [comment]
Этот курс для магистров, если Вы на 4м курсе, то он Вам не подходит. Анкета заполняется только если Вы зашли в университетский gse-Гугл аккаунт.
